// Chirp templates by topic. Variables: {city} {street} {pct} {n} {building}
// {milestone} {unlock} {event} {policy} {season} {temp} {money} {name}.
// Picked deterministically-random by the Chirper; hashtags are part of the fun.

export const CHIRPS: Record<string, readonly string[]> = {
  first_home: [
    'Just got the keys to our new place in {city}! The paint is still wet. #NewBeginnings',
    'We are officially residents of {city}. Population: us, basically. 😄',
    'Moved to {city} for the fresh air and the cheap land. So far so good!',
    'First night in {city}. It is so quiet you can hear the crickets.',
    'Unpacked the last box. {city}, let\'s do this! 📦',
    'Neighbours brought cookies on our first day in {city}. I think we\'ll stay. 🍪',
    'There are more surveyors than people in {city} right now. Exciting times!',
    'Our kids already named every cow in the field behind the house. Welcome to {city}! 🐄',
    'Tiny town, big sky. {city} feels like the start of something.',
    'Mail carrier knows us by name already. Small-town life in {city} is sweet. ✉️',
  ],
  growth: [
    '{city} is growing so fast I barely recognise my own street anymore.',
    'Three new houses went up on {street} this week. Where is everyone coming from?',
    'Construction cranes everywhere in {city}. Love the energy! 🏗️',
    'My commute passes five building sites now. {city} is booming.',
    'Remember when {city} was just a crossroads and a field? Me neither, it was last month.',
    'Real estate agents in {city} have never been busier. #Boomtown',
    'Another family moved in next door. Our street is finally lively!',
    '{city} added {n} residents this month. The bakery can\'t keep up. 🥐',
    'Counted four moving vans on {street} this morning. {city} is on the move! 🚚',
    'The school had to add a new class this year. {city} keeps growing.',
    'New neighbours every week. I\'ve run out of welcome cookies.',
    'Surveyors are marking plots all over the edge of town. More homes coming!',
  ],
  milestone: [
    '{city} just became a {milestone}! Somebody tell my grandma. 🎉',
    'We are a {milestone} now?! Time to update the welcome sign.',
    'Congrats {city} on reaching {milestone} status. The mayor deserves a nap.',
    'Heard the city can now build {unlock}. Big things coming! #Progress',
    'Officially a {milestone}. I feel more sophisticated already. 🎩',
    '{milestone}! Proud to call {city} home.',
    '{milestone}! Somebody order a cake the size of city hall. 🎂',
    'Signs at the city limits now say {milestone}. We made it!',
    'Remember when {city} was a crossroads? Now we\'re a {milestone}.',
    '{city} levelled up to {milestone}. Now unlock me a beach, please.',
  ],
  new_service: [
    'A brand new {building} just opened near me. Finally! 👏',
    'The new {building} looks fantastic. Good job, city hall.',
    'Walked past the new {building} today. Honestly, a game changer for the neighbourhood.',
    'Who else went to the {building} opening? The ribbon cutting was adorable. ✂️',
    'Our taxes at work: a shiny new {building}. I approve.',
    'Can\'t believe we got a {building}. {street} is moving up in the world.',
    'The {building} on {street} opened today. Free coffee for the first visitors! ☕',
    'Finally, a {building} within walking distance. Thank you, {city}!',
    'Checked out the new {building}. Friendly staff, shiny floors. 10/10.',
    'The {building} is exactly what our neighbourhood needed.',
  ],
  traffic_bad: [
    'Sat in traffic for 45 minutes on {street}. I could have walked. 🚗🚗🚗',
    'Whoever designed the intersections in {city} owes me an hour of my life.',
    'Traffic in {city} is a nightmare today. Bring back horses. 🐎',
    'The bus was faster than my car. The bus was stuck too, but less.',
    'I have memorised every pothole on {street} because I spend so long looking at them.',
    'Gridlock again. Maybe more roads? Maybe fewer cars? Maybe a tram? Anything!',
    'Honking does not make traffic move, people. #CityTraffic',
    'Late for work again thanks to the jam near {street}. My boss says hi, mayor.',
  ],
  traffic_good: [
    'Drove across {city} in ten minutes flat. Smooth sailing! 🛣️',
    'Traffic in {city} flows like a dream. Whoever planned these roads: thank you.',
    'Green lights all the way home today. Is this heaven?',
    'Zero traffic jams this week. {city} knows what it\'s doing.',
    'Rush hour in {city} is more like rush minute. 🚦',
    'Made it to the airport with an hour to spare. Traffic here is a dream.',
    'My sat-nav hasn\'t had to reroute me once this month.',
    'Commute on {street} took eight minutes. Eight!',
  ],
  transit_good: [
    'Took the bus to work today. Clean, on time, and I read a whole chapter. 🚌',
    'The new transit line is amazing. Sold my second car!',
    'Public transport in {city} is actually good now. Didn\'t expect that.',
    'Love watching the city roll by from the tram window. 🚋',
    'Transit pass: best money I spend every month.',
    'Bus driver on line 3 waves at every kid on the route. Legend. 🚌',
    'Ditched the car. Transit plus walking = more money for croissants.',
    'Tram at 7:02, coffee at 7:10, desk at 7:15. {city} transit is clockwork.',
  ],
  no_transit: [
    'A city this size and still no buses? Come on, {city}.',
    'Would love to take public transport to work. If only it existed. 🙃',
    'My car is basically my second home at this point. #WeNeedTransit',
    'Waiting for a bus that doesn\'t exist on {street}. Very zen.',
    'Every car in {city} carries exactly one sad commuter. We need buses!',
    'Would ride a bus, tram, train or even a llama to work. Give us options, {city}.',
    'My teenager can\'t drive yet and there\'s no bus. I am now a full-time taxi. 🚕',
  ],
  pollution: [
    'The air near {street} smells like burnt plastic. Is that normal? 😷',
    'Can\'t see the hills anymore through the smog. {city} needs to clean up.',
    'My laundry came off the line grey today. Thanks, factories.',
    'Doctor says my cough is from the pollution. Maybe fewer smokestacks near homes?',
    'Air quality alert again in {city}. Keeping the kids inside. 🏭',
    'The river used to be blue. Now it\'s... a colour. #Pollution',
    'Moved here for the fresh air. Where did it go?',
    'Wiped my car this morning and the cloth came out black. {city}, the air!',
    'Even the pigeons on {street} are coughing. 🐦',
    'Asthma inhaler count in our house: three. Factories nearby: too many.',
  ],
  clean_air: [
    'Breathed in deeply on my morning run. {city} air is so fresh! 🌿',
    'Clear skies, clean air, happy lungs. Love living in {city}.',
    'You can see the stars at night from {street}. No smog at all. ✨',
    'Green city, green lungs. Proud of {city}\'s clean air.',
    'Took a deep breath on {street}. Smelled like cut grass and bakery. Perfect.',
    'Air quality app shows green all week. {city} is doing something right.',
    'Went for a bike ride and didn\'t taste the exhaust once. 🚲',
    'Clean air, clear skies, happy kids. Thanks for keeping {city} green.',
  ],
  no_power: [
    'Power\'s out again on {street}. Candlelit dinner, I guess. 🕯️',
    'My fridge is warm, my phone is dead and my patience is gone. #Blackout',
    'Anybody else\'s lights flickering? Mine just gave up entirely.',
    'Working from home without electricity is just... sitting at home.',
    'The whole block went dark last night. We need more power plants!',
    'Just lost my entire save file to a power cut. Great. 😤',
    'Our street is dark but the stars look amazing. Silver lining, I guess. ✨',
    'Power cut in the middle of the big match. Who do I complain to? ⚡',
    'Bought a generator. Neighbours now visit me to charge their phones.',
  ],
  no_water: [
    'No water coming out of the tap. Showering with bottled water is not glamorous. 🚱',
    'Our water has been off for days on {street}. What is going on, {city}?',
    'Had to boil snow for tea. Okay, I\'m exaggerating. But only a bit.',
    'Dear city: pipes. We need pipes. And water in them.',
    'Tried to wash dishes. The tap coughed at me. 🚱',
    'Had to shower at the gym. I don\'t even go to the gym.',
    'No water on {street} for the third day. My plants are filing complaints. 🌵',
    'Bottled water aisle is empty everywhere. Fix the pumps, {city}!',
  ],
  sewage: [
    'Something smells VERY wrong on {street}. I think the sewers are backed up. 🤢',
    'The toilet gurgles ominously. Please fix the sewage system, {city}.',
    'Sewage problems again. I\'m moving to the woods.',
    'The drains on {street} are bubbling. That\'s never good.',
    'Plumber says it\'s not my pipes, it\'s the city\'s. Great.',
    'Basement smells like regret. Sewage capacity please, {city}! 🤢',
    'Kids asked why the river smells funny. I didn\'t have a good answer.',
  ],
  garbage: [
    'Garbage hasn\'t been picked up in a week on {street}. The raccoons are thrilled. 🦝',
    'The trash pile outside my building has its own ecosystem now.',
    'Can we get a garbage truck to {street}? Please? It\'s getting fragrant.',
    'Overflowing bins everywhere. Is the landfill full or something?',
    'I have started composting out of desperation. Where are the garbage trucks?! 🗑️',
    'Bin day came and went. The bins did not. 🗑️',
    'Seagulls have taken over the trash heap on {street}. They have a leader now.',
    'Pro tip: don\'t walk past the uncollected bins on {street} in summer.',
  ],
  crime: [
    'Someone stole my bike from right outside my door. Third time this year. 🚲',
    'Don\'t feel safe walking home at night on {street} anymore.',
    'More police patrols, please! Break-ins are up in our neighbourhood.',
    'Car window smashed again. {city}, we have a crime problem.',
    'Neighbourhood group chat is 90 % "did anyone else hear that?" lately.',
    'Installed a third lock on my door. Still don\'t sleep well. 🔒',
    'Someone stole the garden gnome. Gerald, come home. 😢',
    'Package thieves strike again on {street}. More patrols please!',
  ],
  safe: [
    'Left my front door unlocked by accident. Nothing happened. Love {city}. 🔓',
    'Walked home at 2 am and felt totally safe. Thank you, police. 👮',
    'Crime is so low here the police officers have time to help cats down from trees.',
    'Kids play outside until the street lights come on. That\'s {city} for you.',
    'Lost my wallet on {street}. Someone returned it with a note. ❤️',
    'Police officer helped me find my runaway dog today. Great service. 🐕',
    'Crime report for our neighbourhood this month: a stolen umbrella. Returned.',
  ],
  sick: [
    'Half my office is out sick. Is something going around in {city}? 🤒',
    'Waited four hours at the clinic today. We need more doctors!',
    'My whole family has the flu. Chicken soup for everyone. 🍲',
    'Can\'t get a doctor\'s appointment for three weeks. Healthcare in {city} needs help.',
    'Clinic waiting room is standing room only. Get well soon, {city}.',
    'Third cold this winter. Maybe it\'s the air, maybe it\'s the kids.',
    'Pharmacy on {street} has a queue out the door. 💊',
    'Doctor told me to rest. I told him the clinic had no beds for me anyway.',
  ],
  no_health: [
    'The hospital was so full they treated me in the hallway. Build more, please!',
    'Nearest clinic is miles away. What if there\'s an emergency? 🚑',
    'Ambulance took 40 minutes to arrive. We need more healthcare in {city}. 🚑',
    'Called three clinics. All full. Please, more doctors!',
    'My GP is booked until next season. Next season!',
    'Waiting room chairs have my back shape memorised now.',
  ],
  dead: [
    'Grandpa passed last week and they still haven\'t come to take him. This is awful. 😢',
    'The funeral home says they\'re "fully booked". What does that even mean?',
    'We need a cemetery or crematorium in {city}. It\'s getting grim.',
    'The hearse never came for Mrs. Novak. Her family is heartbroken.',
    'No room left at the cemetery? What happens now?',
    'Can we please get deathcare sorted, {city}? It\'s undignified.',
  ],
  unemployment: [
    'Sent out 40 applications this month. Zero replies. Jobs, {city}, please. 💼',
    'My whole street is unemployed. We need businesses and factories here.',
    'Spent another day refreshing job sites. Anyone hiring?',
    'Unemployment in {city} is around {pct}. That\'s a lot of us looking.',
    'I have a degree and I\'m unemployed. Office jobs, where are you?',
    'Job fair had 500 people for 12 openings. Rough times in {city}.',
    'Laid off today. Updating my CV and my attitude. 💪',
    'My résumé has more gaps than {street} has potholes.',
  ],
  jobs_good: [
    'Got the job! Starting Monday at a place just down {street}. 🎉',
    'Every shop in {city} has a "Now Hiring" sign. Good times!',
    'Switched jobs twice this year, both times for a raise. {city} economy rocks.',
    'Unemployment basically zero here. Everybody works, everybody eats.',
    'Two job offers in one week! Choices, choices. {city} is booming.',
    'Bosses in {city} are bidding for workers. Salaries going up!',
    'My cousin moved here for work and found a job in three days.',
  ],
  worker_shortage: [
    'Our shop can\'t find staff. Anyone want a job selling very nice socks? 🧦',
    'Factories are begging for workers. {city} needs more residents!',
    'Hiring for three months and zero applicants. Where are the people?',
    'Restaurant on {street} closed early — not enough staff. 😕',
    'Help wanted signs everywhere. Where are all the workers?',
    'Factory manager offered me a job while I was buying bread.',
    'We need more homes so people can move here and work! {city} is short-staffed.',
  ],
  taxes_high: [
    'Taxes in {city} are highway robbery. {pct}?! 💸',
    'My paycheck after taxes looks like a typo.',
    'Thinking of moving to the next town over. Lower taxes, same sunsets.',
    'Dear mayor, I love {city}, but these taxes are brutal.',
    'Did my tax return. Cried a little. {city} taxes at {pct}? Really?',
    'The tax collector knows my name. That\'s not a compliment.',
    'Shop owners on {street} are talking about moving out. Taxes too high.',
  ],
  taxes_low: [
    'Low taxes and good services? {city}, you spoil us. 💰',
    'Tax bill arrived and I laughed. In a good way!',
    'Moved my business to {city} for the low taxes. Best decision ever.',
    'Low taxes, happy wallet. Treating myself to dinner on {street}. 🍝',
    'Friends from the next city are jealous of our tax rates. As they should be.',
    'Opened a small business in {city}. The low taxes made it possible.',
  ],
  happy: [
    'Honestly? {city} is the best place I\'ve ever lived. ❤️',
    'Woke up, saw the sunrise over {city} and smiled. Life is good.',
    'Ten out of ten, would live in {city} again.',
    'Everyone on {street} seems so happy lately. It\'s contagious! 😊',
    'Love this city. Love these people. Love this mayor. (Okay, mostly the people.)',
    'Just realised I\'ve smiled at every stranger on {street} today. {city} does that to you.',
    'Wouldn\'t trade {city} for anywhere else in the world. 🌍',
    'Good schools, clean streets, friendly faces. What more do you want?',
  ],
  unhappy: [
    'Everything in {city} is broken and nobody seems to care. 😠',
    'Seriously considering moving away. This city is going downhill.',
    'Mood in {city} is grim lately. Something needs to change.',
    'I used to brag about {city}. Now I just sigh.',
    'Nobody I know is happy here lately. What happened to {city}?',
    'Checked real estate listings in other cities. Just looking. For now.',
    'Complaints box at city hall is full. Probably mine mostly.',
    '{city} used to be charming. Now it\'s just... tiring. 😞',
  ],
  parks_good: [
    'Picnic in the park with the family today. {city} has the best green spaces. 🌳',
    'Walked the dog through three parks on my way home. Heaven. 🐕',
    'Found a new favourite bench by the fountain. Reading there every Sunday.',
    'Parks in {city} are gorgeous this {season}.',
    'Yoga in the park at sunrise. {city} knows how to live. 🧘',
    'Our kids spent the whole day at the playground. Silent car ride home. Bliss.',
    'Ducks, trees, benches, ice cream. The parks here have it all. 🦆',
  ],
  no_parks: [
    'Is there a single park in {city}? My kids need somewhere to run around. 🌱',
    'Concrete, concrete, concrete. A little greenery would be nice, mayor.',
    'I have to drive out of town to see a tree. Parks please!',
    'My kids think grass is a myth. {city} needs parks! 🌳',
    'Dog keeps looking at me like, where\'s the park? Good question.',
    'A park, a plaza, a tree, anything. Please, {city}.',
  ],
  education_good: [
    'My daughter just got into university! So proud. 🎓',
    'Schools in {city} are excellent. The kids actually like going!',
    'Took an evening class at the library. Never too old to learn.',
    'The teachers here are amazing. {city} invests in its future.',
    'Our high school just won the regional science fair! 🔬',
    'My son explained quantum physics at dinner. Thanks, {city} schools.',
    'Library on {street} is always full of students. Love to see it. 📚',
    'Graduated today! {city} gave me a great education. 🎓',
  ],
  no_school: [
    'Classrooms are packed — 40 kids per teacher. We need more schools!',
    'My son is on a waiting list for school. A waiting list. For school.',
    'Education should be a priority in {city}. More schools, please. 📚',
    'Kids in {city} are being bussed to schools miles away. Not okay.',
    'School is so crowded they\'re teaching in the gym. 🏫',
    'Teacher-to-student ratio in {city} is scary. Build schools please!',
    'My daughter\'s class has no desks left. She sits on a beanbag. For maths.',
  ],
  noise: [
    'Trucks rumbling past {street} all night. I haven\'t slept in days. 😵',
    'Is the construction ever going to stop? My ears are ringing.',
    'Moving next to the highway was a mistake. Earplugs are my best friend.',
    'Bought noise-cancelling headphones just to sleep. Thanks, {street}.',
    'The factory whistle at 6 am is my alarm now. Didn\'t ask for it.',
    'It\'s never quiet on {street}. Never. 🔊',
    'Trying to read in the garden. Hearing only engines and horns.',
  ],
  abandoned: [
    'The empty building on {street} is getting spooky. Broken windows everywhere. 🏚️',
    'Another neighbour packed up and left. The street feels deserted.',
    'Abandoned houses are popping up around town. What happened, {city}?',
    'Boarded-up windows on {street}. Makes me sad every time I walk past.',
    'The old house down the road has been empty for months. Feels haunted. 👻',
    'Why are people leaving {city}? Somebody fix whatever\'s broken.',
    'Graffiti on the empty building on {street} is actually really good. Still sad though.',
  ],
  high_rent: [
    'My rent went up again. {city} is getting too expensive for regular folks. 🏠',
    'Land values are skyrocketing. Great if you own, terrible if you rent.',
    'Landlord raised the rent 20 %. {city}, I love you, but come on.',
    'Rent in {city} is now my biggest expense. Bigger than food. Bigger than joy.',
    'Neighbourhood got fancy and now I can\'t afford to live in it. 🏠',
    'Three roommates and a cat, still barely making rent. #CityLife',
  ],
  no_goods: [
    'The supermarket shelves on {street} are empty again. 🛒',
    'Shops can\'t get stock. Do we even have factories in {city}?',
    'Hardware store on {street} is out of everything. We need more industry!',
    'Tried to buy a new phone charger. Out of stock for weeks. 📦',
    'Shops in {city} are waiting on deliveries that never come.',
    'Empty shelves, empty trolleys, empty promises. Goods, please!',
  ],
  shops_wanted: [
    'I have to drive 20 minutes for groceries. Where are the shops in {city}?',
    'Would love a café on {street}. Just saying. ☕',
    'So many houses, so few stores. Someone open a bakery!',
    'Nearest bakery is a 30 minute walk. That\'s not a lifestyle, that\'s a pilgrimage.',
    '{city} needs shops! I want to spend my money here, not in the next town.',
    'Main street needs a bookshop, a café and a florist. In that order.',
  ],
  homes_wanted: [
    'Looking for an apartment in {city} and there is literally nothing available. 🏘️',
    'Everyone wants to move to {city} but there are no homes left!',
    'Housing waitlist in {city} is longer than my arm.',
    'Viewed an apartment with 30 other people. {city} needs more homes!',
    'Sleeping on my friend\'s couch until a place opens up. Any day now. 🛋️',
    'Friends want to move to {city} but can\'t find a single flat.',
  ],
  tourism: [
    'So many tourists in {city} today! Our little town is famous. 📸',
    'A tourist asked me for directions to the {building}. Felt like an ambassador.',
    'Hotels are fully booked this weekend. {city} is on the map!',
    'Tourists everywhere with maps and ice cream. Business is great for the shops.',
    'Tour bus parked on {street} again. Our street is famous!',
    'Visitors love the {building}. I love the new ice cream stand next to it. 🍦',
    'Sold 50 postcards at my shop today. Thanks, tourists! 📮',
    'Heard six languages on the way to work today. {city} is going global. 🌍',
  ],
  budget_bad: [
    'Heard the city is broke. Should I be worried about my garbage collection? 😬',
    'City finances in the red again. Maybe fewer golden statues, mayor?',
    'Dear city hall: budgets are like diets. Hard, but necessary.',
    'City is in debt again. Maybe sell the mayor\'s fancy chair?',
    'Rumour says services will be cut. Hope it\'s not the parks. 😬',
    'Red ink everywhere at city hall. Hope they have a plan.',
  ],
  level5: [
    'The new tower on {street} is incredible. {city} has a real skyline now! 🏙️',
    'Watched them top out the skyscraper today. It\'s taller than I imagined.',
    'Our city is growing up — literally. Look at that tower!',
    'Our new skyscraper has a rooftop garden. City views for days. 🌇',
    'Neck hurts from looking up at the new tower on {street}.',
    'Skyline of {city} looks like a proper metropolis now. So proud.',
  ],
  disaster: [
    'Stay safe everyone! {event} hitting {city} right now. ⚠️',
    'Did everyone survive the {event}? Checking in on neighbours on {street}.',
    'That {event} was terrifying. Thank you, emergency services! 🚒',
    'Cleaning up after the {event}. {city} is tough, we\'ll rebuild. 💪',
    'Never thought I\'d live through a {event}. Hug your loved ones.',
    'Emergency crews working through the night after the {event}. Heroes. 🦸',
    'Power\'s back, roads are clearing. {city} bounces back from the {event}.',
    'Donating blankets and food for families hit by the {event}. Let\'s help each other.',
  ],
  event_good: [
    '{event} in {city} today! Best day of the year. 🎉',
    'Who else is at the {event}? The atmosphere is electric!',
    'The {event} brought so many people to town. Loved it.',
    'Streets full of music and people for the {event}. {city} knows how to party! 🎶',
    'Took the whole family to the {event}. Memories for life.',
    'The {event} was the talk of the town. When\'s the next one?',
    'Best. Weekend. Ever. Thanks for the {event}, {city}! 🎉',
  ],
  policy: [
    'Heard the city passed "{policy}". About time!',
    'Not sure how I feel about "{policy}". We\'ll see. 🤔',
    'New policy: {policy}. Mayor\'s been busy.',
    '"{policy}" is now law in {city}. Mixed feelings on my street.',
    'Finally a mayor who does things. "{policy}"? I\'m in.',
    'Reading the fine print on "{policy}". Seems sensible, actually.',
    'My neighbour is FURIOUS about "{policy}". I think it\'s great.',
  ],
  weather_rain: [
    'Rain, rain, go away… or stay, the garden loves it. 🌧️',
    'Forgot my umbrella AGAIN. Soaked on {street}.',
    'Cozy rainy day in {city}. Tea and a book. ☕📖',
    'Puddle jumping with the kids. Best kind of rainy day.',
    'Rainy {season} day. Perfect excuse to stay in and bake bread. 🍞',
    'Water in the gutters on {street} is basically a river now.',
  ],
  weather_snow: [
    'Snow day in {city}! Built a snowman on {street}. ⛄',
    'The city looks magical under all this snow. ❄️',
    'Shovelled the driveway three times today. Winter, please chill. Oh wait.',
    'Snowball fight on {street}! The neighbours started it. ☃️',
    'Sledding hill packed with kids and suspiciously competitive parents.',
    'Snow ploughs out early this morning. Roads looking good, {city}! 🚜',
  ],
  weather_heat: [
    'It\'s {temp} outside. I am melting. 🥵',
    'Heatwave in {city}. Every fan in the store is sold out.',
    'The pool is packed and the ice cream truck is a hero today. 🍦',
    'Cooked an egg on the pavement of {street}. Did not eat it. 🍳',
    'AC broke. Living in the freezer aisle of the supermarket now.',
    '{temp} and rising. Stay hydrated, {city}! 💧',
  ],
  weather_storm: [
    'That thunder just rattled my windows! ⛈️',
    'Storm knocked a branch onto my car. Stay inside, {city}.',
    'Lightning show over {city} tonight was spectacular. And scary.',
    'Storm siren just went off. Everyone stay safe indoors! 🌩️',
    'Trees down on {street} after the storm. Crews already on it.',
    'Wind howling like a freight train. {city}, hold on to your hats.',
  ],
  weather_fog: [
    'Fog so thick on {street} I walked into a lamp post. 🌫️',
    'Foggy morning in {city}. Very mysterious. Very damp.',
    'Fog rolled in over {city} like a blanket. Very moody. Very photogenic. 📷',
    'Couldn\'t see the end of {street} this morning. Drive carefully!',
    'Foggy day, cozy café, good book. Perfect.',
  ],
  weather_clear: [
    'Gorgeous blue sky over {city} today! ☀️',
    'Perfect weather for a walk along {street}.',
    'Not a cloud in the sky. {city} is showing off.',
    'Sun\'s out, everyone\'s out. {city} parks are packed today. 😎',
    'Clear skies tonight — perfect for stargazing over {city}. 🌌',
    'Blue sky, light breeze, {temp}. Ideal.',
  ],
  season_spring: [
    'Cherry blossoms are out in {city}! Spring is here. 🌸',
    'Birds singing, flowers blooming. Spring in {city} is the best.',
    'Tulips along {street} are in full bloom. Spring has sprung! 🌷',
    'Spring cleaning done. Now for the garden. 🌱',
    'First ice cream of the year on {street}. It\'s official: spring. 🍦',
  ],
  season_summer: [
    'Summer in {city} means barbecues on {street} every weekend. 🌭',
    'Long summer evenings are the best. Sunset at 9 pm!',
    'Beach towel, sunscreen, cold drink. Summer in {city} is on. 🏖️',
    'Fireflies in the park tonight. Summer magic. ✨',
    'Outdoor cinema in the park this summer. {city} gets it.',
  ],
  season_autumn: [
    'The trees along {street} are gold and red. Autumn in {city} is stunning. 🍂',
    'Pumpkin spice season has arrived in {city}. You\'ve been warned.',
    'Jumped in a leaf pile on {street}. No regrets. 🍁',
    'Apple picking season! The orchards outside {city} are packed.',
    'Cosy jumpers and misty mornings. Autumn in {city}. ☕',
  ],
  season_winter: [
    'Hot chocolate weather in {city}. ☕❄️',
    'Winter lights are up on {street}. So pretty!',
    'Christmas market on {street} smells like cinnamon and roasted nuts. 🎄',
    'Frosty morning, every rooftop in {city} sparkling. ❄️',
    'Ice skating rink opened downtown. Fell twice. Loved it. ⛸️',
  ],
  generic: [
    'Found the best taco place in {city}. Not telling where. 🌮',
    'My cat judged me all day. Just another Tuesday in {city}. 🐈',
    'Ran my first 10k along {street}! Legs are jelly.',
    'The sunset over {city} tonight was unreal. 🌅',
    'Somebody on {street} is learning trumpet. Good for them. Bad for us.',
    'Local band played on the corner of {street} today. So good!',
    'Coffee, check. Commute, check. Existential dread, check. Good morning {city}!',
    'Adopted a dog today. His name is Mayor. 🐶',
    'Farmers market this weekend was amazing. Bought way too many tomatoes. 🍅',
    'Spotted a fox on {street} at dawn. City wildlife is the best. 🦊',
    'Just finished a jigsaw of the {city} skyline. Meta.',
    'Why does every pigeon in {city} know where I eat lunch?',
    'Our street party was a blast. Thanks, neighbours!',
    'Tried to parallel park on {street}. Gave up. Walked.',
    'Is it just me or is the moon extra big over {city} tonight? 🌕',
    'Grandma just learned to use Chirper. Hi grandma! 👵',
    'Today I learned {city} has a street named {street}. Charming.',
    'Weekend plans: absolutely nothing, in {city}. Perfect.',
    'Office birthday cake count this week: 3. Gym count: 0. 🎂',
    'My kid asked why the sky is blue. I said "city regulations". Nailed it.',
    'The bakery on {street} just started making croissants. I am in danger. 🥐',
    'Book club tonight at the café. Nobody read the book. Classic.',
    'Tried the new ramen spot on {street}. I\'d move here for it alone. 🍜',
    'Street musician on {street} played my wedding song. Cried a little. 🎻',
    'My neighbour\'s rooster thinks 4 am is a great time. It is not.',
    'Found a twenty in my winter coat. Best day in {city} ever. 💵',
    'Chess tournament in the park today. Grandpa won. Grandpa always wins. ♟️',
    'Saw a double rainbow over {city}. What does it mean?! 🌈',
    'Library fine forgiveness day! Returning books from 2019. Don\'t judge.',
    'The ice cream truck plays a song I can\'t get out of my head. Help.',
    'Our block has a group chat. It\'s 80 % lost cats and 20 % found cats. 🐈',
    'Took the long way home along {street}. Worth it for the view.',
    'Local newspaper headline: \'Man finds slightly larger potato\'. Slow news day in {city}. 🥔',
    'Pizza delivery arrived in 12 minutes. {city} efficiency.',
    'Volunteered at the food bank today. {city} has a big heart. ❤️',
    'Someone on {street} built a tiny free library. Community goals. 📚',
  ],
  night: [
    'City lights of {city} from my balcony tonight. Unreal. 🌃',
    'Can\'t sleep. The city hums at night. Kind of beautiful.',
    'Late-night noodles on {street}. The only correct choice. 🍜',
    'Night shift crew, where you at? {city} never really sleeps. 🌙',
    'Street lights on {street} make everything look like a movie set.',
    'Midnight walk through {city}. Quiet, calm, perfect.',
    'Owls hooting over {street}. Didn\'t know we had owls! 🦉',
  ],
  event_bad: [
    'The {event} is hitting {city} hard. Hang in there, everyone.',
    'Everybody\'s talking about the {event}. Nobody\'s happy about it. 😟',
    'Hope the {event} blows over soon. {city} deserves a break.',
    'Tough week in {city} with the {event}. We\'ll get through it.',
  ],
  fire: [
    'Smoke over {street}! Fire trucks on the way. Stay safe! 🔥',
    'Building fire near {street}. Hope everyone got out okay. 🚒',
    'Saw the flames from my window. Thank you firefighters for the fast response.',
    'Another fire in {city}? We need more fire stations. 🧯',
  ],
  loan: [
    'City took out a loan. Hope they spend it on something good. 🏦',
    'Heard {city} borrowed money. Future me will pay for this, right?',
    'Big loan for {city}. Big plans, hopefully!',
  ],
  tax_raise: [
    'Taxes going UP in {city}? Just when I bought a new couch. 💸',
    'Mayor raised taxes. Better see better roads for it!',
    'Tax hike announced. My wallet heard and fainted.',
    'Higher taxes, eh? I expect gold-plated bin collection then.',
  ],
  tax_cut: [
    'Tax cut in {city}! Drinks are on me. Well, one drink. 🍻',
    'Lower taxes? The mayor might just get my vote again.',
    'Thanks for the tax cut, {city}. Saving it for a rainy day. ☔',
  ],
  new_line: [
    'New transit line launched! Rode it end to end just for fun. 🚆',
    'The new line stops right outside my door. Life changing!',
    'Public transport expanding in {city}. Car-free life, here I come.',
  ],
  landmark: [
    'The {building} is breathtaking. {city} has a new icon! 🏛️',
    'Took 200 photos of the {building} today. Zero regrets. 📷',
    'Tourists are already queueing at the {building}. Proud of {city}!',
    'Our grandchildren will visit the {building} one day. History in the making.',
  ],
  offices: [
    'New office tower going up on {street}. Suits and lattes everywhere. ☕',
    'Landed a job at one of the new offices in {city}. Corner desk!',
    '{city} is turning into a proper business hub.',
  ],
  exports: [
    'Trucks full of {city}-made goods heading out every morning. 🚛',
    'Our factory ships to half the country now. Made in {city}!',
    'Local products on shelves in other cities. That\'s our stuff! 📦',
  ],
  education_bad: [
    'Most people I meet in {city} left school early. We need better education.',
    'Offices won\'t come here without educated workers. Schools, please!',
    'My kid wants to be an engineer. Nearest good school is miles away. 🎒',
  ],
};

/** icon per topic for the notice */
export const CHIRP_ICONS: Record<string, string> = {
  traffic_bad: '🚗', traffic_good: '🛣️', transit_good: '🚌', no_transit: '🚏', pollution: '🏭', clean_air: '🌿', no_power: '⚡',
  no_water: '🚱', sewage: '🚽', garbage: '🗑️', crime: '🚨', safe: '👮', sick: '🤒', no_health: '🏥', dead: '⚰️', unemployment: '💼',
  jobs_good: '🎉', worker_shortage: '🧑‍🏭', taxes_high: '💸', taxes_low: '💰', happy: '😊', unhappy: '😠', parks_good: '🌳',
  no_parks: '🌱', education_good: '🎓', no_school: '📚', noise: '🔊', abandoned: '🏚️', high_rent: '🏠', no_goods: '🛒',
  shops_wanted: '🛍️', homes_wanted: '🏘️', tourism: '📸', budget_bad: '📉', level5: '🏙️', disaster: '⚠️', event_good: '🎊',
  policy: '📜', weather_rain: '🌧️', weather_snow: '❄️', weather_heat: '🥵', weather_storm: '⛈️', weather_fog: '🌫️',
  weather_clear: '☀️', season_spring: '🌸', season_summer: '🌞', season_autumn: '🍂', season_winter: '⛄', generic: '🐦',
  night: '🌙', first_home: '🏡', growth: '🏗️', milestone: '🏆', new_service: '✨', event_bad: '😟', fire: '🔥', loan: '🏦',
  tax_raise: '💸', tax_cut: '💰', new_line: '🚆', landmark: '🏛️', offices: '🏢', exports: '🚛', education_bad: '🎒',
};
