// Chirp templates by topic. Variables: {city} {street} {pct} {n} {building}
// {milestone} {unlock} {event} {policy} {season} {temp} {money} {name}.
// Picked deterministically-random by the Chirper; hashtags are part of the fun.

export const CHIRPS: Record<string, readonly string[]> = {
  first_home: [
    'Just got the keys to our new place in {city}! The paint is still wet. #NewBeginnings',
    'We are officially residents of {city}. Population: us, basically. 😄',
    'Moved to {city} for the fresh air and the cheap land. So far so good!',
    'First night in {city}. It is so quiet you can hear the crickets.',
    'Unpacked the last box. {city}, let\'s do this! 📦',
    'Neighbours brought cookies on our first day in {city}. I think we\'ll stay. 🍪',
    'There are more surveyors than people in {city} right now. Exciting times!',
  ],
  growth: [
    '{city} is growing so fast I barely recognise my own street anymore.',
    'Three new houses went up on {street} this week. Where is everyone coming from?',
    'Construction cranes everywhere in {city}. Love the energy! 🏗️',
    'My commute passes five building sites now. {city} is booming.',
    'Remember when {city} was just a crossroads and a field? Me neither, it was last month.',
    'Real estate agents in {city} have never been busier. #Boomtown',
    'Another family moved in next door. Our street is finally lively!',
    '{city} added {n} residents this month. The bakery can\'t keep up. 🥐',
  ],
  milestone: [
    '{city} just became a {milestone}! Somebody tell my grandma. 🎉',
    'We are a {milestone} now?! Time to update the welcome sign.',
    'Congrats {city} on reaching {milestone} status. The mayor deserves a nap.',
    'Heard the city can now build {unlock}. Big things coming! #Progress',
    'Officially a {milestone}. I feel more sophisticated already. 🎩',
    '{milestone}! Proud to call {city} home.',
  ],
  new_service: [
    'A brand new {building} just opened near me. Finally! 👏',
    'The new {building} looks fantastic. Good job, city hall.',
    'Walked past the new {building} today. Honestly, a game changer for the neighbourhood.',
    'Who else went to the {building} opening? The ribbon cutting was adorable. ✂️',
    'Our taxes at work: a shiny new {building}. I approve.',
    'Can\'t believe we got a {building}. {street} is moving up in the world.',
  ],
  traffic_bad: [
    'Sat in traffic for 45 minutes on {street}. I could have walked. 🚗🚗🚗',
    'Whoever designed the intersections in {city} owes me an hour of my life.',
    'Traffic in {city} is a nightmare today. Bring back horses. 🐎',
    'The bus was faster than my car. The bus was stuck too, but less.',
    'I have memorised every pothole on {street} because I spend so long looking at them.',
    'Gridlock again. Maybe more roads? Maybe fewer cars? Maybe a tram? Anything!',
    'Honking does not make traffic move, people. #CityTraffic',
    'Late for work again thanks to the jam near {street}. My boss says hi, mayor.',
  ],
  traffic_good: [
    'Drove across {city} in ten minutes flat. Smooth sailing! 🛣️',
    'Traffic in {city} flows like a dream. Whoever planned these roads: thank you.',
    'Green lights all the way home today. Is this heaven?',
    'Zero traffic jams this week. {city} knows what it\'s doing.',
  ],
  transit_good: [
    'Took the bus to work today. Clean, on time, and I read a whole chapter. 🚌',
    'The new transit line is amazing. Sold my second car!',
    'Public transport in {city} is actually good now. Didn\'t expect that.',
    'Love watching the city roll by from the tram window. 🚋',
    'Transit pass: best money I spend every month.',
  ],
  no_transit: [
    'A city this size and still no buses? Come on, {city}.',
    'Would love to take public transport to work. If only it existed. 🙃',
    'My car is basically my second home at this point. #WeNeedTransit',
  ],
  pollution: [
    'The air near {street} smells like burnt plastic. Is that normal? 😷',
    'Can\'t see the hills anymore through the smog. {city} needs to clean up.',
    'My laundry came off the line grey today. Thanks, factories.',
    'Doctor says my cough is from the pollution. Maybe fewer smokestacks near homes?',
    'Air quality alert again in {city}. Keeping the kids inside. 🏭',
    'The river used to be blue. Now it\'s... a colour. #Pollution',
    'Moved here for the fresh air. Where did it go?',
  ],
  clean_air: [
    'Breathed in deeply on my morning run. {city} air is so fresh! 🌿',
    'Clear skies, clean air, happy lungs. Love living in {city}.',
    'You can see the stars at night from {street}. No smog at all. ✨',
    'Green city, green lungs. Proud of {city}\'s clean air.',
  ],
  no_power: [
    'Power\'s out again on {street}. Candlelit dinner, I guess. 🕯️',
    'My fridge is warm, my phone is dead and my patience is gone. #Blackout',
    'Anybody else\'s lights flickering? Mine just gave up entirely.',
    'Working from home without electricity is just... sitting at home.',
    'The whole block went dark last night. We need more power plants!',
    'Just lost my entire save file to a power cut. Great. 😤',
  ],
  no_water: [
    'No water coming out of the tap. Showering with bottled water is not glamorous. 🚱',
    'Our water has been off for days on {street}. What is going on, {city}?',
    'Had to boil snow for tea. Okay, I\'m exaggerating. But only a bit.',
    'Dear city: pipes. We need pipes. And water in them.',
  ],
  sewage: [
    'Something smells VERY wrong on {street}. I think the sewers are backed up. 🤢',
    'The toilet gurgles ominously. Please fix the sewage system, {city}.',
    'Sewage problems again. I\'m moving to the woods.',
  ],
  garbage: [
    'Garbage hasn\'t been picked up in a week on {street}. The raccoons are thrilled. 🦝',
    'The trash pile outside my building has its own ecosystem now.',
    'Can we get a garbage truck to {street}? Please? It\'s getting fragrant.',
    'Overflowing bins everywhere. Is the landfill full or something?',
    'I have started composting out of desperation. Where are the garbage trucks?! 🗑️',
  ],
  crime: [
    'Someone stole my bike from right outside my door. Third time this year. 🚲',
    'Don\'t feel safe walking home at night on {street} anymore.',
    'More police patrols, please! Break-ins are up in our neighbourhood.',
    'Car window smashed again. {city}, we have a crime problem.',
    'Neighbourhood group chat is 90 % "did anyone else hear that?" lately.',
  ],
  safe: [
    'Left my front door unlocked by accident. Nothing happened. Love {city}. 🔓',
    'Walked home at 2 am and felt totally safe. Thank you, police. 👮',
    'Crime is so low here the police officers have time to help cats down from trees.',
  ],
  sick: [
    'Half my office is out sick. Is something going around in {city}? 🤒',
    'Waited four hours at the clinic today. We need more doctors!',
    'My whole family has the flu. Chicken soup for everyone. 🍲',
    'Can\'t get a doctor\'s appointment for three weeks. Healthcare in {city} needs help.',
  ],
  no_health: [
    'The hospital was so full they treated me in the hallway. Build more, please!',
    'Nearest clinic is miles away. What if there\'s an emergency? 🚑',
  ],
  dead: [
    'Grandpa passed last week and they still haven\'t come to take him. This is awful. 😢',
    'The funeral home says they\'re "fully booked". What does that even mean?',
    'We need a cemetery or crematorium in {city}. It\'s getting grim.',
  ],
  unemployment: [
    'Sent out 40 applications this month. Zero replies. Jobs, {city}, please. 💼',
    'My whole street is unemployed. We need businesses and factories here.',
    'Spent another day refreshing job sites. Anyone hiring?',
    'Unemployment in {city} is around {pct}. That\'s a lot of us looking.',
    'I have a degree and I\'m unemployed. Office jobs, where are you?',
  ],
  jobs_good: [
    'Got the job! Starting Monday at a place just down {street}. 🎉',
    'Every shop in {city} has a "Now Hiring" sign. Good times!',
    'Switched jobs twice this year, both times for a raise. {city} economy rocks.',
    'Unemployment basically zero here. Everybody works, everybody eats.',
  ],
  worker_shortage: [
    'Our shop can\'t find staff. Anyone want a job selling very nice socks? 🧦',
    'Factories are begging for workers. {city} needs more residents!',
    'Hiring for three months and zero applicants. Where are the people?',
  ],
  taxes_high: [
    'Taxes in {city} are highway robbery. {pct}?! 💸',
    'My paycheck after taxes looks like a typo.',
    'Thinking of moving to the next town over. Lower taxes, same sunsets.',
    'Dear mayor, I love {city}, but these taxes are brutal.',
  ],
  taxes_low: [
    'Low taxes and good services? {city}, you spoil us. 💰',
    'Tax bill arrived and I laughed. In a good way!',
    'Moved my business to {city} for the low taxes. Best decision ever.',
  ],
  happy: [
    'Honestly? {city} is the best place I\'ve ever lived. ❤️',
    'Woke up, saw the sunrise over {city} and smiled. Life is good.',
    'Ten out of ten, would live in {city} again.',
    'Everyone on {street} seems so happy lately. It\'s contagious! 😊',
    'Love this city. Love these people. Love this mayor. (Okay, mostly the people.)',
  ],
  unhappy: [
    'Everything in {city} is broken and nobody seems to care. 😠',
    'Seriously considering moving away. This city is going downhill.',
    'Mood in {city} is grim lately. Something needs to change.',
    'I used to brag about {city}. Now I just sigh.',
  ],
  parks_good: [
    'Picnic in the park with the family today. {city} has the best green spaces. 🌳',
    'Walked the dog through three parks on my way home. Heaven. 🐕',
    'Found a new favourite bench by the fountain. Reading there every Sunday.',
    'Parks in {city} are gorgeous this {season}.',
  ],
  no_parks: [
    'Is there a single park in {city}? My kids need somewhere to run around. 🌱',
    'Concrete, concrete, concrete. A little greenery would be nice, mayor.',
    'I have to drive out of town to see a tree. Parks please!',
  ],
  education_good: [
    'My daughter just got into university! So proud. 🎓',
    'Schools in {city} are excellent. The kids actually like going!',
    'Took an evening class at the library. Never too old to learn.',
    'The teachers here are amazing. {city} invests in its future.',
  ],
  no_school: [
    'Classrooms are packed — 40 kids per teacher. We need more schools!',
    'My son is on a waiting list for school. A waiting list. For school.',
    'Education should be a priority in {city}. More schools, please. 📚',
  ],
  noise: [
    'Trucks rumbling past {street} all night. I haven\'t slept in days. 😵',
    'Is the construction ever going to stop? My ears are ringing.',
    'Moving next to the highway was a mistake. Earplugs are my best friend.',
  ],
  abandoned: [
    'The empty building on {street} is getting spooky. Broken windows everywhere. 🏚️',
    'Another neighbour packed up and left. The street feels deserted.',
    'Abandoned houses are popping up around town. What happened, {city}?',
  ],
  high_rent: [
    'My rent went up again. {city} is getting too expensive for regular folks. 🏠',
    'Land values are skyrocketing. Great if you own, terrible if you rent.',
  ],
  no_goods: [
    'The supermarket shelves on {street} are empty again. 🛒',
    'Shops can\'t get stock. Do we even have factories in {city}?',
  ],
  shops_wanted: [
    'I have to drive 20 minutes for groceries. Where are the shops in {city}?',
    'Would love a café on {street}. Just saying. ☕',
    'So many houses, so few stores. Someone open a bakery!',
  ],
  homes_wanted: [
    'Looking for an apartment in {city} and there is literally nothing available. 🏘️',
    'Everyone wants to move to {city} but there are no homes left!',
    'Housing waitlist in {city} is longer than my arm.',
  ],
  tourism: [
    'So many tourists in {city} today! Our little town is famous. 📸',
    'A tourist asked me for directions to the {building}. Felt like an ambassador.',
    'Hotels are fully booked this weekend. {city} is on the map!',
    'Tourists everywhere with maps and ice cream. Business is great for the shops.',
  ],
  budget_bad: [
    'Heard the city is broke. Should I be worried about my garbage collection? 😬',
    'City finances in the red again. Maybe fewer golden statues, mayor?',
    'Dear city hall: budgets are like diets. Hard, but necessary.',
  ],
  level5: [
    'The new tower on {street} is incredible. {city} has a real skyline now! 🏙️',
    'Watched them top out the skyscraper today. It\'s taller than I imagined.',
    'Our city is growing up — literally. Look at that tower!',
  ],
  disaster: [
    'Stay safe everyone! {event} hitting {city} right now. ⚠️',
    'Did everyone survive the {event}? Checking in on neighbours on {street}.',
    'That {event} was terrifying. Thank you, emergency services! 🚒',
    'Cleaning up after the {event}. {city} is tough, we\'ll rebuild. 💪',
    'Never thought I\'d live through a {event}. Hug your loved ones.',
  ],
  event_good: [
    '{event} in {city} today! Best day of the year. 🎉',
    'Who else is at the {event}? The atmosphere is electric!',
    'The {event} brought so many people to town. Loved it.',
  ],
  policy: [
    'Heard the city passed "{policy}". About time!',
    'Not sure how I feel about "{policy}". We\'ll see. 🤔',
    'New policy: {policy}. Mayor\'s been busy.',
  ],
  weather_rain: [
    'Rain, rain, go away… or stay, the garden loves it. 🌧️',
    'Forgot my umbrella AGAIN. Soaked on {street}.',
    'Cozy rainy day in {city}. Tea and a book. ☕📖',
    'Puddle jumping with the kids. Best kind of rainy day.',
  ],
  weather_snow: [
    'Snow day in {city}! Built a snowman on {street}. ⛄',
    'The city looks magical under all this snow. ❄️',
    'Shovelled the driveway three times today. Winter, please chill. Oh wait.',
  ],
  weather_heat: [
    'It\'s {temp} outside. I am melting. 🥵',
    'Heatwave in {city}. Every fan in the store is sold out.',
    'The pool is packed and the ice cream truck is a hero today. 🍦',
  ],
  weather_storm: [
    'That thunder just rattled my windows! ⛈️',
    'Storm knocked a branch onto my car. Stay inside, {city}.',
    'Lightning show over {city} tonight was spectacular. And scary.',
  ],
  weather_fog: [
    'Fog so thick on {street} I walked into a lamp post. 🌫️',
    'Foggy morning in {city}. Very mysterious. Very damp.',
  ],
  weather_clear: [
    'Gorgeous blue sky over {city} today! ☀️',
    'Perfect weather for a walk along {street}.',
    'Not a cloud in the sky. {city} is showing off.',
  ],
  season_spring: [
    'Cherry blossoms are out in {city}! Spring is here. 🌸',
    'Birds singing, flowers blooming. Spring in {city} is the best.',
  ],
  season_summer: [
    'Summer in {city} means barbecues on {street} every weekend. 🌭',
    'Long summer evenings are the best. Sunset at 9 pm!',
  ],
  season_autumn: [
    'The trees along {street} are gold and red. Autumn in {city} is stunning. 🍂',
    'Pumpkin spice season has arrived in {city}. You\'ve been warned.',
  ],
  season_winter: [
    'Hot chocolate weather in {city}. ☕❄️',
    'Winter lights are up on {street}. So pretty!',
  ],
  generic: [
    'Found the best taco place in {city}. Not telling where. 🌮',
    'My cat judged me all day. Just another Tuesday in {city}. 🐈',
    'Ran my first 10k along {street}! Legs are jelly.',
    'The sunset over {city} tonight was unreal. 🌅',
    'Somebody on {street} is learning trumpet. Good for them. Bad for us.',
    'Local band played on the corner of {street} today. So good!',
    'Coffee, check. Commute, check. Existential dread, check. Good morning {city}!',
    'Adopted a dog today. His name is Mayor. 🐶',
    'Farmers market this weekend was amazing. Bought way too many tomatoes. 🍅',
    'Spotted a fox on {street} at dawn. City wildlife is the best. 🦊',
    'Just finished a jigsaw of the {city} skyline. Meta.',
    'Why does every pigeon in {city} know where I eat lunch?',
    'Our street party was a blast. Thanks, neighbours!',
    'Tried to parallel park on {street}. Gave up. Walked.',
    'Is it just me or is the moon extra big over {city} tonight? 🌕',
    'Grandma just learned to use Chirper. Hi grandma! 👵',
    'Today I learned {city} has a street named {street}. Charming.',
    'Weekend plans: absolutely nothing, in {city}. Perfect.',
    'Office birthday cake count this week: 3. Gym count: 0. 🎂',
    'My kid asked why the sky is blue. I said "city regulations". Nailed it.',
    'The bakery on {street} just started making croissants. I am in danger. 🥐',
    'Book club tonight at the café. Nobody read the book. Classic.',
  ],
  night: [
    'City lights of {city} from my balcony tonight. Unreal. 🌃',
    'Can\'t sleep. The city hums at night. Kind of beautiful.',
    'Late-night noodles on {street}. The only correct choice. 🍜',
  ],
};

/** icon per topic for the notice */
export const CHIRP_ICONS: Record<string, string> = {
  traffic_bad: '🚗', traffic_good: '🛣️', transit_good: '🚌', no_transit: '🚏', pollution: '🏭', clean_air: '🌿', no_power: '⚡',
  no_water: '🚱', sewage: '🚽', garbage: '🗑️', crime: '🚨', safe: '👮', sick: '🤒', no_health: '🏥', dead: '⚰️', unemployment: '💼',
  jobs_good: '🎉', worker_shortage: '🧑‍🏭', taxes_high: '💸', taxes_low: '💰', happy: '😊', unhappy: '😠', parks_good: '🌳',
  no_parks: '🌱', education_good: '🎓', no_school: '📚', noise: '🔊', abandoned: '🏚️', high_rent: '🏠', no_goods: '🛒',
  shops_wanted: '🛍️', homes_wanted: '🏘️', tourism: '📸', budget_bad: '📉', level5: '🏙️', disaster: '⚠️', event_good: '🎊',
  policy: '📜', weather_rain: '🌧️', weather_snow: '❄️', weather_heat: '🥵', weather_storm: '⛈️', weather_fog: '🌫️',
  weather_clear: '☀️', season_spring: '🌸', season_summer: '🌞', season_autumn: '🍂', season_winter: '⛄', generic: '🐦',
  night: '🌙', first_home: '🏡', growth: '🏗️', milestone: '🏆', new_service: '✨',
};
